### ISSUE TITLE
不支持Java17以下的版本启动

### ISSUE THREAD

**Issue by SulfuricM** [YuxuanZuo/MultiYggdrasil#11]
Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE199E bad major version 61.0 of class=xyz/zuoyx/multiyggdrasil/Premain, the maximum supported major version is 55.0; offset=6
        at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.base/java.lang.ClassLoader.defineClassInternal(Unknown Source)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422

Fatal error: processing of -javaagent failed, processJavaStart failed

**Comment by YuxuanZuo** [comment]
抱歉，开发的时候用到了一些高版本Java的特性，所以只能使用Java17启动了
