### ISSUE TITLE
[BUG?] 启动失败：发现在 fabric 端与 Mythicmetals 等模组冲突

### ISSUE THREAD

**Issue by Moetazhxi** [YuxuanZuo/MultiYggdrasil#18]
**服务器类型：**
Fabric 1.20.1

**测试环境：**
Windows / Linux 均试过，报错一样

**Java 版本：**
17 / 18 / 21 均尝试过，报错大差不差

**已装模组：**
\- alloy_forgery 2.1.2+1.20
\- cardinal-components 5.2.2
\- fabric-api 0.91.0+1.20.1
**\- mythicmetals 0.19.2+1.20.1（主模组，其他四个都是前置）**
\- owo 0.11.2+1.20

**启动参数：**
```
java -Xmx8G  -javaagent:.\MultiYggdrasil-0.3.0-all.jar=https://littleskin.cn/api/yggdrasil -jar fabric-server-launch.jar nogui
pause
```

**完整日志信息：**
```
[MultiYggdrasil] [INFO] Logging file: ****\MultiYggdrasil.log
[MultiYggdrasil] [INFO] Version: 0.3.0
[MultiYggdrasil] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil
[MultiYggdrasil] [INFO] Disabled Mojang Yggdrasil service
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[17:24:18] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.24
[17:24:18] [main/WARN]: Warnings were found!
 - Mod 'Alloy Forgery' (alloy_forgery) 2.1.2+1.20 recommends version 12.0.0 or later of roughlyenoughitems, which is missing!
         - You should install version 12.0.0 or later of roughlyenoughitems for the optimal experience.
[17:24:18] [main/INFO]: Loading 60 mods:
        - alloy_forgery 2.1.2+1.20
        - cardinal-components 5.2.2
           |-- cardinal-components-base 5.2.2
           |-- cardinal-components-block 5.2.2
           |-- cardinal-components-chunk 5.2.2
           |-- cardinal-components-entity 5.2.2
           |-- cardinal-components-item 5.2.2
           |-- cardinal-components-level 5.2.2
           |-- cardinal-components-scoreboard 5.2.2
           \-- cardinal-components-world 5.2.2
        - fabric-api 0.91.0+1.20.1
           |-- fabric-api-base 0.4.30+7abfd51577
           |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
           |-- fabric-biome-api-v1 13.0.12+215bbe9677
           |-- fabric-block-api-v1 1.0.10+92a0d36777
           |-- fabric-block-view-api-v2 1.0.0+92a0d36777
           |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
           |-- fabric-client-tags-api-v1 1.1.1+97bb207577
           |-- fabric-command-api-v1 1.2.33+f71b366f77
           |-- fabric-command-api-v2 2.2.12+b3afc78b77
           |-- fabric-commands-v0 0.2.50+df3654b377
           |-- fabric-containers-v0 0.1.63+df3654b377
           |-- fabric-content-registries-v0 4.0.10+57aed33f77
           |-- fabric-convention-tags-v1 1.5.4+a1a980da77
           |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
           |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
           |-- fabric-dimensions-v1 2.1.53+8536527b77
           |-- fabric-entity-events-v1 1.5.22+b3afc78b77
           |-- fabric-events-interaction-v0 0.6.1+e91849a877
           |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
           |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
           |-- fabric-item-api-v1 2.1.27+b3afc78b77
           |-- fabric-item-group-api-v1 4.0.11+d7b148e077
           |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
           |-- fabric-keybindings-v0 0.2.34+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
           |-- fabric-loot-api-v2 1.2.0+96dfa95977
           |-- fabric-loot-tables-v1 1.1.44+9e7660c677
           |-- fabric-message-api-v1 5.1.8+d7b148e077
           |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
           |-- fabric-model-loading-api-v1 1.0.2+709a987177
           |-- fabric-models-v0 0.4.1+9386d8a777
           |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
           |-- fabric-networking-v0 0.3.50+df3654b377
           |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
           |-- fabric-particles-v1 1.1.1+201a23a077
           |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
           |-- fabric-registry-sync-v0 2.3.2+4df89eb277
           |-- fabric-renderer-api-v1 3.2.0+39a511ba77
           |-- fabric-renderer-indigo 1.5.0+39a511ba77
           |-- fabric-renderer-registries-v1 3.2.45+df3654b377
           |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
           |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
           |-- fabric-rendering-v0 1.1.48+df3654b377
           |-- fabric-rendering-v1 3.0.7+b3afc78b77
           |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
           |-- fabric-resource-loader-v0 0.11.9+132c48c177
           |-- fabric-screen-api-v1 2.0.7+b3afc78b77
           |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
           |-- fabric-sound-api-v1 1.0.12+b3afc78b77
           |-- fabric-transfer-api-v1 3.3.3+c81d263177
           \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
        - fabricloader 0.14.24
        - java 18
        - minecraft 1.20.1
        - mythicmetals 0.19.2+1.20.1
           |-- additionalentityattributes 1.4.0+1.20.0
           |    \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
           |-- com_github_llamalad7_mixinextras 0.2.0-beta.6
           |-- common-protection-api 1.0.0
           |-- mm_shedaniel 2.4.1
           \-- reach-entity-attributes 2.4.0
        - owo 0.11.2+1.20
           \-- blue_endless_jankson 1.2.2
[17:24:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:****/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[17:24:18] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-launch.jar:0.11.2]
Caused by: java.lang.RuntimeException: Error creating Mixin config additionalentityattributes.mixins.json for mod additionalentityattributes
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        ... 1 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config additionalentityattributes.mixins.json
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        ... 1 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 18.0, ASM 9.0 (ASM10_EXPERIMENTAL))
        at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        ... 1 more
```

**附：**
Mythicmetals 模组：https://modrinth.com/mod/mythicmetals
经测试，使用 https://github.com/yushijinhun/authlib-injector 时并没有出现此问题，服务器可以正常启动。

**Comment by YuxuanZuo** [comment]
已修复，能麻烦您测试一下吗
https://github.com/YuxuanZuo/MultiYggdrasil/actions/runs/7766619256/artifacts/1217309226

**Comment by Moetazhxi** [comment]
> 已修复，能麻烦您测试一下吗 https://github.com/YuxuanZuo/MultiYggdrasil/actions/runs/7766619256/artifacts/1217309226

启动成功了！感谢作者，辛苦辽！！

**Comment by Moetazhxi** [comment]
> 已修复，能麻烦您测试一下吗 https://github.com/YuxuanZuo/MultiYggdrasil/actions/runs/7766619256/artifacts/1217309226

不知道是不是我的问题，我这里第三方验证玩家能看到自己和正版玩家的皮肤，正版玩家只能看到正版玩家的皮肤，看不到第三方验证玩家的皮肤，版本是 1.20.1

**Comment by YuxuanZuo** [comment]
是正常现象，正版玩家没有皮肤站签名导致的，可以试试SkinsRestorer这类插件手动切换皮肤

**Comment by Moetazhxi** [comment]
> 是正常现象，正版玩家没有皮肤站签名导致的，可以试试SkinsRestorer这类插件手动切换皮肤

okok，感谢解答！
