### ISSUE TITLE
1.18.2arclight核心启动崩溃

### ISSUE THREAD

**Issue by YinHuansleep** [YuxuanZuo/MultiYggdrasil#21]
[MultiYggdrasil] [INFO] Logging file: D:\qiangda\MultiYggdrasil.log
[MultiYggdrasil] [INFO] Version: 0.3.0
[MultiYggdrasil] [INFO] Authentication server:
[MultiYggdrasil] [INFO] Mojang Yggdrasil service is enabled, Mojang namespace will be disabled!
[MultiYggdrasil] [INFO] Disabled Mojang namespace
java.lang.IllegalStateException: Package org/objectweb/asm for module org.objectweb.asm is already in the unnamed module defined to the class loader
        at java.base/java.lang.Module.defineModule0(Native Method)
        at java.base/java.lang.Module.<init>(Module.java:137)
        at java.base/java.lang.Module.defineModules(Module.java:1183)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at io.izzel.arclight.forgeinstaller.ForgeInstaller.addModules(ForgeInstaller.java:530)
        at io.izzel.arclight.forgeinstaller.ForgeInstaller.classpath(ForgeInstaller.java:328)
        at io.izzel.arclight.forgeinstaller.ForgeInstaller.applicationInstall(ForgeInstaller.java:110)
        at io.izzel.arclight.boot.application.Main_Forge.forgeInstall(Main_Forge.java:41)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:19)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Fail to launch Arclight.

**Comment by YinHuansleep** [comment]
启动参数加入-Dauthlibinjector.ignoredPackages=org.objectweb.asm也没用
