### ISSUE TITLE
1.21fabric服务端无法启动

### ISSUE THREAD

**Issue by MatchMan-qwq** [YuxuanZuo/MultiYggdrasil#22]
报错如下
Exception in thread "main" java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71)
Caused by: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/C:/Users/Administrator/Desktop/MCDR/server/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar!/org/objectweb/asm/ClassReader.class, jar:file:/C:/Users/Administrator/Desktop/MCDR/server/MultiYggdrasil-0.3.0-all.jar!/org/objectweb/asm/ClassReader.class
        at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:79)
        at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:345)
        ... 2 more

**Comment by MatchMan-qwq** [comment]
这是完整的日志

C:\Users\Administrator\Desktop\MCDR\server>"C:\Program Files\Java\jdk-21\bin\java.exe" -Dfile.encoding=UTF-8 -Xms6G -Xmx7G -javaagent:MultiYggdrasil-0.3.0-all.jar=https://littleskin.cn/api/yggdrasil/ -Dmultiyggdrasil.mojangYggdrasilService=enabled -Dmultiyggdrasil.namespace=skin -jar fabric-server-launch.jar nogui
[MultiYggdrasil] [INFO] Logging file: C:\Users\Administrator\Desktop\MCDR\server\MultiYggdrasil.log
[MultiYggdrasil] [INFO] Version: 0.3.0
[MultiYggdrasil] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil/
[MultiYggdrasil] [INFO] Mojang Yggdrasil service is enabled, Mojang namespace will be disabled!
[MultiYggdrasil] [INFO] Disabled Mojang namespace
Exception in thread "main" java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71)
Caused by: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/C:/Users/Administrator/Desktop/MCDR/server/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar!/org/objectweb/asm/ClassReader.class, jar:file:/C:/Users/Administrator/Desktop/MCDR/server/MultiYggdrasil-0.3.0-all.jar!/org/objectweb/asm/ClassReader.class
        at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:79)
        at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:345)
        ... 2 more

C:\Users\Administrator\Desktop\MCDR\server>pause
请按任意键继续. . .
